### ISSUE TITLE
Data not Generating

### ISSUE THREAD

**Issue by Cronvall** [albinens/IMSX16_Kandidatarbete#6]
Jag tror inte jag får datan på backenden att generaras. Se .env och bilder nedan.

### .env
```
# This file is populated with the default values
# for the development environment. You can change
# the values to match your environment.

INFLUXDB_TOKEN=liveinfo! # This is the token used to authenticate with InfluxDB
INFLUXDB_URL=http://localhost:8086 # This is the URL of the InfluxDB instance, including the port

POSTGRES_USERNAME=liveinfo # This is the username used to authenticate with the Postgres database
POSTGRES_PASSWORD=liveinfo # This is the password used to authenticate with the Postgres database


PORT=8080 # The port the server will listen on

```
### exposed port results
![Screenshot 2024-03-05 at 10 01 18](https://github.com/albinens/IMSX16_Kandidatarbete/assets/47293083/492a552e-64e0-407f-bf03-4598ebfa86c4)

### Fail when running go
Go instansen kraschar inte men skickar ut failed (tror det har att göra med något i postgres).
![Screenshot 2024-03-05 at 09 26 01](https://github.com/albinens/IMSX16_Kandidatarbete/assets/47293083/0948d7ce-4718-4c7b-97fb-201065539d77)

### Docker
Jag får båda containersen att köra (postgres & influxdb) och kommer åt influxdb sidan på 8086
Har svårt att tro att Docker är det som förstör här.

### Influx
Är det tänkt att jag ska ladda ner dependencies på frontenden för att querry:a?
Känns fuffens att man skapar dependencies på en databas bibliotek för att få ut data...

http://localhost:8086/orgs/f839646cfbf7146d/new-user-setup/nodejs

**Comment by Supergamer1337** [comment]
Testa att stänga ner containers, och ta bort datan. Sen kan du testa att starta upp docker-compose igen _och vänta i typ 30 sekunder_. Har märkt att om man är för snabb kan man få detta problemet, för att databaserna inte initieras korrekt vid first boot

**Comment by Cronvall** [comment]
Får denna goingen nu
![Screenshot 2024-03-05 at 10 24 05](https://github.com/albinens/IMSX16_Kandidatarbete/assets/47293083/e9932093-2981-4fca-9c21-846294eb95ed)

**Comment by Supergamer1337** [comment]
Hmm, det har jag inte sett tidigare... Kan behöva undersöka när jag kommer hem
